CQCL/tket2

pyrs/src/optimiser.rs
src/optimiser/taso.rs
src/optimiser/taso/log.rs
taso-optimiser/src/main.rs

Adds a `-q`/`--queue-size` parameter, that defaults to 10_000.
Drive-by: Slight reformatting of the log output.

feat: queue size argument for TASO

---

Cargo.toml
tket2/src/json/encoder.rs

`PrimValue` was flattened in https://github.com/CQCL/hugr/pull/685

chore: Update hugr dep

---

tket2-py/src/circuit.rs
tket2-py/src/passes.rs
tket2/benches/benchmarks/generators.rs
tket2/src/circuit.rs
tket2/src/circuit/command.rs
tket2/src/circuit/cost.rs
tket2/src/circuit/hash.rs
tket2/src/extension.rs
tket2/src/json/encoder.rs
tket2/src/json/op.rs
tket2/src/json/tests.rs
tket2/src/lib.rs
tket2/src/ops.rs
tket2/src/optimiser/badger.rs
tket2/src/optimiser/badger/qtz_circuit.rs
tket2/src/passes/chunks.rs
tket2/src/passes/commutation.rs
tket2/src/portmatching/matcher.rs
tket2/src/portmatching/pattern.rs
tket2/src/rewrite/ecc_rewriter.rs
tket2/src/rewrite/strategy.rs

For consistency with `Tk2Circuit`

refactor: rename t2op

---

badger-optimiser/src/main.rs

Check the ECC file extension and load it accordingly.

feat: Load pre-compiled ECCs in the badger runner

---

tket2/src/json/op.rs
tket2/src/ops.rs

feat: add qalloc, qfree, reset ops

---

Cargo.toml
tket2/Cargo.toml
tket2/src/extension/angle.rs

- CustomConst changed
- update strum

chore: update to hugr 0.2

---

tket2-py/test/test_pass.py

test producing a depth conversion bug, now succeeds after basing on main
Closes #286

test: depth pass conversion error

---

.github/workflows/pr-title.yml
.github/workflows/release-please.yml
.github/workflows/release-plz.yml

Uses @hugrbot's token in CI, so messages and tokens are created with its username.

ci: Use hugrbot in automation

---

README.md
release-plz.toml

drive-by: Fix two links in the README

ci: Enable release-plz publish to crates.io

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml
tket2-py/src/ops.rs
tket2-py/src/pattern.rs
tket2-py/src/pattern/portmatching.rs
tket2-py/test/test_pass.py
tket2-py/test/test_pauli_prop.py
tket2-py/tket2/_tket2/ops.pyi
tket2-py/tket2/_tket2/optimiser.pyi
tket2-py/tket2/_tket2/passes.pyi
tket2-py/tket2/_tket2/pattern.pyi
tket2-py/tket2/passes.py

Re-enables mypy on the pre-commit checks now that we have typing info on the bindings, and fixes all errors.
We are not checking this in CI yet. I'll put that in a separate PR with other CI changes.

chore: Fix mypy lints

---

Cargo.lock
Cargo.toml
tket2/src/passes/pytket.rs
tket2/src/serialize/pytket/op/native.rs

This should unblock #475
Edit: No, it wont. It is still blocked on a separate bug -.-

chore(deps-rs): Update hugr and tket-json-rs

---

Cargo.lock
Cargo.toml

chore(deps-rs): Update to hugr 0.9.1

---

.github/workflows/python-pure-wheels.yml

Fix #523 not actually running the pure wheel building steps...
Now that that got merged to main I was able to _workflow dispatch_ it to test, and it seems I used the wrong syntax for the ifs.
It works now:
https://github.com/CQCL/tket2/actions/runs/10214055732/job/28260696536

ci: Fix pure wheels if check

---

Cargo.lock
tket2/src/lib.rs

Closes #651
drive by: cargo update

feat: re-export hugr crate

---

.github/workflows/ci.yml

Using the instructions from [hugrverse-actions](https://github.com/CQCL/hugrverse-actions?tab=readme-ov-file#rs-semver-checks)

ci: Run cargo-semver-checks on PRs

---

tket2-hseries/src/extension/futures.rs
tket2-hseries/src/extension/result.rs
tket2-py/examples/utils/__init__.py
tket2/src/circuit/command.rs
tket2/src/optimiser/badger/log.rs
tket2/tests/badger_termination.rs
uv.lock

chore: Fix new lints in Rust 1.83

---

devenv.lock
devenv.yaml
tket2/src/circuit/command.rs
tket2/src/serialize/pytket/param/encode.rs
uv.lock

uv 0.5.15 and rust 1.84
+ clippy fixes

chore: devenv update

---

DEVELOPMENT.md
tket2-exts/README.md
tket2-exts/src/tket2_exts/__init__.py
tket2-exts/src/tket2_exts/data/tket2/qsystem/utils.json
tket2-hseries/README.md
tket2-hseries/src/bin/tket2-hseries.rs
tket2-hseries/src/extension.rs
tket2-hseries/src/extension/utils.rs
tket2-py/tket2/extensions/__init__.py
uv.lock

feat: add a `tket2.qsystem.utils` extension with `GetCurrentShot`

---

tket2-exts/src/tket2_exts/data/tket2/qsystem/utils.json
tket2-hseries/src/extension/utils.rs

Closes: #789
BREAKING CHANGE:
This adds an entry to the `UtilsOp` enum. Now it looks like this:
```
tket2_hseries::extension::utils
pub enum UtilsOp {
GetCurrentShot,
OrderInZones,
}
```

feat(tket2-hseries)!: Add order_in_zones extension op

---

release-please-config.json

See guppy PR for more detailed info: https://github.com/CQCL/guppylang/pull/870

ci: Update uv.lock on release-please PRs

---

.github/workflows/ci.yml

See https://github.com/CQCL/hugr/pull/2374.
[error](https://github.com/CQCL/tket2/actions/runs/15875744214/job/44762805647#step:4:29)

ci: Fix extension version check on main

---

tket2/src/llvm.rs
tket2/src/llvm/bool.rs
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@llvm14_1.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@llvm14_2.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@llvm14_3.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@llvm14_4.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@llvm14_5.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@llvm14_6.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@llvm14_7.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@pre-mem2reg@llvm14_1.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@pre-mem2reg@llvm14_2.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@pre-mem2reg@llvm14_3.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@pre-mem2reg@llvm14_4.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@pre-mem2reg@llvm14_5.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@pre-mem2reg@llvm14_6.snap
tket2/src/llvm/snapshots/tket2__llvm__bool__test__emit_all_ops@pre-mem2reg@llvm14_7.snap

Copied over from Guppy, closes #909

feat: Add llvm codegen for `tket2.bool`

---

tket-py/test/test_optimiser.py

So we can make a release with #1075.
BEGIN_COMMIT_OVERRIDE
feat: Capture pytket's output permutation explicitly in the hugr connectivity (#1075)
END_COMMIT_OVERRIDE
...#1076 didn't actually touch the python files -.-
I swear I'm not farming github stats.

chore: Dummy change to trigger python release

---

tket/src/resource.rs

ci: Pacify miri

---

tket/src/serialize/pytket/encoder.rs
tket/src/serialize/pytket/tests.rs

When encoding a hugr into a pytket circuit, we use a toposort over the given region to process nodes.
This skips over non-local edges, and caused the encoding to fail due to the input wires not being registered.
This PR adds a check before processing each node that looks at any incoming non-local edge and
- If it is a module-level definition of a float/rotation parameter, loads it.
- If it is a module-level function definition/declaration, we know function-typed wires don't carry pytket values so we mark them as such.
- Anything else (e.g. a non-local edge from a parent DF region) causes the node itself to be marked as unsupported.

feat: Deal with non-local edges in pytket encoder
