- pyrs/src/optimiser.rs
- src/optimiser/taso.rs
- src/optimiser/taso/hugr_pchannel.rs
- src/optimiser/taso/hugr_pqueue.rs
- taso-optimiser/src/main.rs
Instead of cutting the truncating in half, we just pop the last element before inserting if we're at capacity.
Sets the new default size to 100, as that is more sensible for our workloads.
> feat: Trim TASO priority queue progresively

- pyrs/Cargo.toml
- pyrs/nam_6_3.rwr
- pyrs/src/lib.rs
- pyrs/src/optimiser.rs
- pyrs/src/pass.rs
- pyrs/test/test_optimiser.py
- pyrs/test/test_pass.py
- src/lib.rs
- src/ops.rs
This is a useful Python binding to create the pytket-hyper extension on top of.
> feat: Add Python TASO pass

- src/circuit/cost.rs
- src/optimiser/taso.rs
- src/optimiser/taso/hugr_pchannel.rs
- src/optimiser/taso/hugr_pqueue.rs
- src/optimiser/taso/log.rs
- src/optimiser/taso/worker.rs
- taso-optimiser/src/main.rs
The main feature of this PR is reducing the memory usage of multithreading with a priority channel by adding a shared `Arc<RwLock<Option<P>>>` with the maximum circuit cost in the queue, so the workers don't fill the channels with useless data.
The main improvement of this is limiting the memory usage when multiple threads are involved. Now I can run `barenco_tof_10` on 10 threads with ~4GB of RAM, where before it exceeded 10GB (and caused a OOM).
I also included multiple small changes extracted from #175;
- `CircuitCost::as_usize` instead of proxy operations, so we can share cost limits as atomics and run other primitive operations directly.
- Print the actual number of circuits processed on the log (not only the seen count, which includes elements in the queue).
- Replace `eprintln!`s …
> feat: Multithreading improvements

- .github/workflows/ci.yml
- .github/workflows/unsoundness.yml
- Move from [rust-cache](https://github.com/Swatinem/rust-cache) to [sccache](https://github.com/Mozilla-Actions/sccache-action). This has helped in other crates, but I can't say I see an improvement yet. I'll monitor it once it's being used.
- Move the python bindings to their own job. This is where most of the CI time is being spent, so it makes sense to run it directly from the beginning. I added a python cache and excluded this from the merge queue checks.
- Stop testing on the rust `nightly` channel. This test is mostly to report back any breaks but the cache gets invalidated daily, adding to the CI times. Testing on `beta` should suffice.
> ci: Various improvements

- Cargo.toml
- pyrs/Cargo.toml
Final update in the dependency tree: now all crates use `pyo3 0.20`.
BREAKING CHANGE: Updated `pyo3` to `0.20` all dependencies must have matching versions due to it linking to the python lib.
> chore(deps)!: Update deps

- src/passes/chunks.rs
- src/portmatching/matcher.rs
The latest hugr update dropped the mut requirement in `SiblingSubgraph`.
> feat: Do not require &mut ConvexCheckers

- Cargo.toml
- taso-optimiser/Cargo.toml
- taso-optimiser/src/main.rs
Also enables thin LTO on release builds.
Tested on `barenco_tof_10`, 10s timeout, single threaded, on my laptop.
Before / after:
> perf: Use jemallocator by default for taso

- .github/workflows/ci.yml
- README.md
This one includes pytest coverage in addition to rust tests.
https://app.codecov.io/gh/CQCL/tket2/tree/ci%2Fcodecov
> ci: Check coverage with codecov

- Cargo.toml
- tket2/Cargo.toml
- tket2/src/circuit.rs
- tket2/src/circuit/command.rs
- tket2/src/circuit/units.rs
- tket2/src/passes/chunks.rs
- tket2/src/portmatching.rs
- tket2/src/portmatching/matcher.rs
- tket2/src/portmatching/pattern.rs
- tket2/src/portmatching/pyo3.rs
This required a partial move from using `Port` everywhere to the more specific `OutgoingPort` and `IncomingPort`.
I'll open a separate issue for the more pervasive changes like updating the `Units` iterator and the `portmatching` module.
For now, we just cast and `unwrap` in those cases.
Requires https://github.com/CQCL/hugr/pull/647
> chore: update hugr dependency

- Cargo.toml
- devenv.lock
- devenv.nix
- tket2/src/extension.rs
- tket2/src/ops.rs
api change to `instantiate_concrete` -> `instantiate`
rust 1.73
devenv uses poetry
> chore: update devenv and hugr

- Cargo.toml
- tket2/src/extension.rs
- tket2/src/extension/angle.rs
- tket2/src/ops.rs
moved from hugr https://github.com/CQCL/hugr/pull/670
Closes #217
> feat: add angle type to tket2 extension 

- .github/workflows/ci.yml
#211 didn't update the coverage path in `ci.yml` x_x
> ci: fix failing py coverage upload

- tket2/src/optimiser/badger.rs
Timeout=0, so runtime impact is minimal, and it's kept deterministic; the loop quits immediately and no rewrites are applied.
> test: Add small parallel badger test

- tket2/src/optimiser/badger.rs
We shouldn't check the optimised circuit vs a fixed output.
This fixes some spurious test failures:
https://github.com/CQCL/tket2/actions/runs/6876784637/job/18703089884?pr=244
> test: fix non-deterministic badger test

- pyproject.toml
- tket2-py/src/circuit.rs
- tket2-py/src/circuit/convert.rs
- tket2-py/src/optimiser.rs
- tket2-py/src/passes.rs
- tket2-py/src/passes/chunks.rs
- tket2-py/src/pattern.rs
- tket2-py/src/pattern/portmatching.rs
- tket2-py/test/test_bindings.py
Adds a `tket1`/`tket2` to the `with_hugr` helpers, so we always know what format to output afterwards.
The more noisy part of this commit changing all the GIL-independent types to capturing references, so we don't have to manually lock multiple times per call.
Closes #178.
> feat: Use tket1 and tket2 circuits interchangeably everywhere

- docs/quantum.md
There was no obvious place to put this text so I created a `docs` directory.
> docs: Port text deleted in https://github.com/CQCL/hugr/pull/694 .

- pyproject.toml
poetry was throwing an error due to the invalid field
> fix: Invalid licence attribute in pyproject

- Cargo.toml
- tket2-py/Cargo.toml
- tket2-py/src/lib.rs
- tket2/Cargo.toml
- tket2/benches/bench_main.rs
- tket2/src/circuit/command.rs
- tket2/src/circuit/units.rs
- tket2/src/extension.rs
- tket2/src/extension/angle.rs
- tket2/src/json/decoder.rs
- tket2/src/json/op.rs
- tket2/src/lib.rs
- tket2/src/portmatching.rs
- tket2/src/portmatching/pattern.rs
- tket2/src/rewrite/ecc_rewriter.rs
- Updates the API changes introduced in https://github.com/CQCL/hugr/pull/680
- Uses the latest published portmatching instead of a git dependency
- Moves the lint configuration to the workspace Cargo.toml (new to rust [1.74](https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html))
This throws warnings in older rust versions due to the unrecognised fields, but works alright.
> chore: update deps

- tket2-py/tket2/passes.py
- tket2-py/tket2/rewrite.py
For some reason this failed in python310 with error
```
AttributeError: module 'importlib' has no attribute 'resources'
```
This fix _seems_ to work, although I'm not sure why it didn't work on the first place...
> fix: failed importlib import

- tket2/src/circuit/hash.rs
- tket2/src/optimiser/badger.rs
- tket2/src/optimiser/badger/hugr_pqueue.rs
- tket2/src/optimiser/badger/worker.rs
This is a short-term quick-but-incomplete fix for #239.
We now check right after the composition whether we have invalidated the circuit by making a loop.
We leverage that circuit hashing already does a toposort traversal, adding an error when a loop is found and catching it.
Still, it is theoretically possible for an invalid chain of rewrites to end up producing a valid (but not equivalent) circuit. There is a discussion open for discussing more general solutions to this problem #242.
> fix: Check for rewrite composition in badger

- tket2-py/Cargo.toml
- tket2-py/src/circuit.rs
- tket2-py/src/circuit/convert.rs
- tket2-py/src/lib.rs
- tket2-py/src/passes.rs
- tket2-py/src/passes/chunks.rs
- tket2-py/src/pattern.rs
- tket2-py/src/utils.rs
- tket2/src/json.rs
- tket2/src/passes.rs
- tket2/src/passes/commutation.rs
- tket2/src/portmatching/pattern.rs
With this we can drop the `pyo3` features in hugr and portgraph.
`tket2` and `tket-json-rs` still require it, as they define some non-error pyclasses.
This requires manually converting errors by calling `convert_pyerrs` before `?`, but it is a small price to pay for not dealing with pyo3 versions across crates.
> feat: Implement `PyErr` conversion locally in `tket2-py`

- badger-optimiser/src/main.rs
- tket2-py/src/optimiser.rs
- tket2-py/src/passes.rs
- tket2/src/optimiser/badger.rs
- tket2/tests/badger_termination.rs
Stops the optimisation when we haven't found any new best results in a while.
> feat: Add a "progress timeout" to badger

- Cargo.toml
- tket2/src/extension/angle.rs
- tket2/src/json/decoder.rs
- tket2/src/json/tests.rs
- tket2/src/passes/chunks.rs
- tket2/src/portmatching/matcher.rs
- `ConvexChecker` is now a trait.
- `CustomConst` knows it's extension id.
> chore: update hugr dep

- README.md
- badger-optimiser/Cargo.toml
- badger-optimiser/src/main.rs
- tket2/Cargo.toml
- tket2/src/optimiser/badger.rs
- tket2/src/optimiser/badger/log.rs
- tket2/src/rewrite.rs
- tket2/src/rewrite/strategy.rs
- tket2/src/rewrite/trace.rs
Optionally store metadata about the rewrites applied to a circuit.
If the `rewrite-tracing` feature is disabled, this has no effect on the runtime.
If the feature is enabled, circuits must opt-in to the tracing by calling `RewriteTracer::enable_rewrite_tracing`.
Closes #216
> feat: rewrite tracing

- tket2/src/optimiser/badger/hugr_pqueue.rs
I'm not sure why CI didn't catch these
> chore: Ignore unused warnings

- tket2/src/ops.rs
Opaque ops weren't being decoded.
> fix: Encode opaque symbolic constants

- tket2/src/rewrite/strategy.rs
Expose the rewrite cost delta functions
> feat: Move pre/post rewrite cost to the RewriteStrategy API

- tket2/src/optimiser/badger.rs
- tket2/src/optimiser/badger/worker.rs
- tket2/src/rewrite/strategy.rs
...instead of collecting a vector and returning it.
This lets us generate rewrites on-demand, so we avoid unnecessary work.
Closes #269
> feat: Return rewrite strategies as a generator

- Cargo.toml
- tket2/src/circuit/command.rs
- tket2/src/circuit/units.rs
- tket2/src/json/tests.rs
Uses the new static port methods in OpType
Adds a test to ensure we're correctly using the ports methods in the Commands iterator.
(the update broke the circuits iterator)
> chore: update hugr

- tket2/src/portmatching.rs
- tket2/src/portmatching/matcher.rs
In addition to the getter methods for `PatternMatch`, adds an example in the `portmatching` module docs using it.
Closes #297 .
> feat: Add `PatternMatch::nodes` and `subcircuit` + matching example

- tket2/src/circuit/command.rs
- tket2/src/ops.rs
- tket2/src/passes/commutation.rs
a TODO was written for exposing the name as a public function on Tk2Op to avoid intos at caller
also update the comment on the impl of Rewrite of PullForward to reflect change in hugr
> feat: expose Tk2Op name

- .github/workflows/pr-title.yml
Don't insert github expressions directly in the bash script.
- It breaks if there are [backticks] or [quotes] inside the variable.
- It's a security issue, it allows arbitrary code injections from the PR description.
The solution is to put them into env variables first.
> ci(pr-title): Escape variables used in bash scripts

- tket2/src/json/op.rs
Throws an error instead of converting the operation into one with different signature.
Fixes #330
> fix: Don't convert tket2 measurements into tket1 ops

- tket2-py/src/circuit.rs
- tket2-py/src/circuit/convert.rs
- tket2-py/src/circuit/tk2circuit.rs
- tket2-py/src/passes/chunks.rs
- tket2-py/src/pattern.rs
Adds a `tk2circuit.rs` file with the definition of a (python-binded) circuit, instead of leaving it in `convert.rs`.
> refactor: Move `Tk2Circuit` to its own file

- release-plz.toml
Otherwise release-plz tries to generate changelogs for `tket2-py` and the binary tools.
https://github.com/CQCL/tket2/pull/357
> ci: whitelist packages to release-plz

- Cargo.lock
- pyproject.toml
- tket2-py/src/circuit.rs
- tket2-py/src/pattern.rs
- tket2-py/src/pattern/portmatching.rs
- tket2-py/tket2/_tket2/circuit.pyi
- tket2-py/tket2/_tket2/optimiser.pyi
- tket2-py/tket2/_tket2/passes.pyi
- tket2-py/tket2/_tket2/pattern.pyi
- tket2-py/tket2/_tket2/rewrite.pyi
- tket2-py/tket2/pattern.py
Adds typing info for the currently binded classes and methods.
Also binds a couple classes that where missing.
Fixes #342.
> feat: Add missing typing hints

- .github/change-filters.yml
- .github/workflows/ci.yml
- DEVELOPMENT.md
Bring the conditional CI checks from hugr, so we don't run unnecessary steps all the time and we can parallelise a bit more.
If the PR is labelled with `run-ci-checks`, it will run all the checks independently of the changed files.
I'll update the repo `required` checks before merging this.
> ci: Conditional checks based on changed files

- tket2/src/circuit/command.rs
- tket2/src/utils.rs
The commands iterator did a toposort on the whole Hugr, ignoring the hierarchy.
This generated problems with #370, since circuits may now be nested somewhere in the hugr.
It would also have caused problems with circuit boxes, but we don't support that yet here.
We use a `SiblingGraph` now, to ensure that we only explore the top-level region of the circuit.
Subcircuits will be returned as a single command.
Adds a `build_module_with_circuit` helper to build circuits inside modules.
Closes #42.
> fix: Commands iterator ignoring the hierarchy.

- tket2/build.rs
Rust 1.80 will require pre-declaring configuration flags that we want to set via RUSTFLAGS.
See the [blog post](https://blog.rust-lang.org/2024/05/06/check-cfg.html).
Fixes #383
> chore: Declare ci_run flag in build.rs

- tket2/src/circuit.rs
- tket2/src/lib.rs
- tket2/src/optimiser/badger/eq_circ_class.rs
- tket2/src/portmatching/pattern.rs
- tket2/src/rewrite.rs
- tket2/src/rewrite/strategy.rs
Closes #105. Closes #108.
`num_gates` used to count every node in the top-level region, giving unexpected results on results with constants, control flow, or anything other than simple gates.
`num_operations` now only counts `CustomOp`s, traversing containers as needed.
I also improved the circuit unit tests, to include circuits in modules and circuits in `FuncDefn`s (instead of `DFG`s).
Some notes:
- Part of the tests testing parametric operations is commented out until we solve https://github.com/CQCL/hugr/issues/1166.
- Although the test circuits have function names, `Circuit::name` returns `None`. I'll address that in another PR.
> feat: Replace `Circuit::num_gates` with `num_operations`

- .github/workflows/python-wheels.yml
The `if` condition that decided whether to publish to pypi always evaluate to `true` -.-
I'm still not sure why; I suspected the trailing `||` but I tested many variations and only this github expression in a single line worked as expected...
https://github.com/CQCL/tket2/actions/runs/9418704582/job/25947230967
> ci: Fix release wheels if condition

- tket2/src/circuit.rs
Returns a subset of `Circuit::commands`, corresponding to the commands counted by `Circuit::num_operations`.
This is useful to ignore `LoadConst`s and tuple operations when we only care about "gate like" operations in the circuit. But mainly, it's meant as an iterator with similar behaviour to `num_operations`.
Note that #199 is still an open issue; tuple operations in the middle of the circuit may result in confusing linear indices.
> feat: `Circuit::operations`

- Cargo.lock
- tket2/src/circuit.rs
- tket2/src/passes/chunks.rs
- tket2/src/rewrite/strategy.rs
- tket2/src/serialize/pytket/decoder.rs
- Stores the circuit name in the `FuncDefn` operations instead of a "name" metadata key.
In the future we will decode tket1 circuits into funtion definitions instead of Dfg blocks, but that currently causes errors due to https://github.com/CQCL/hugr/issues/1175.
- `Circuit::circuit_signature` returns a `FunctionType` instead of a `PolyFuncType`, since we (currently) don't allow parametric signatures.
- Improves the errors when constructing and manipulating circuits.
This work is in the path to solving #385 and #389, but we will require some fixes in hugr (https://github.com/CQCL/hugr/pull/1177) before fixing the support for non-Dfg rooted circuits.
> fix: Single source of truth for circuit names, and better circuit errors

- Cargo.lock
- Cargo.toml
- tket2/Cargo.toml
- tket2/src/circuit.rs
- tket2/src/circuit/extract_dfg.rs
- tket2/src/portmatching/matcher.rs
- tket2/src/rewrite.rs
- tket2/src/serialize/pytket/decoder.rs
- tket2/src/utils.rs
Followup to #390.
Fixes #389.
Closes #385.
~~Blocked by https://github.com/CQCL/hugr/issues/1175.~~
Fixes support for non-`Dfg` circuits and circuits with a non-root parent:
Adds a `Circuit::extract_dfg(&self)` function that extracts the circuit into a new hugr with a DFG operation at the root.
In some cases, like in a CFG DataflowBlock node, this requires some changes to the definition to eliminate the output sum type.
Here I only implemented it for the kind of blocks produced by guppy. We could replace the manual implementation once https://github.com/CQCL/hugr/issues/818 gets implemented.
With this we can now fix #389 by extracting the circuit before using it as a replacement in `SimpleReplacement::create_simple_replacement`.
Replaces `DfgBuilder` with `FunctionBuilder` where possible, …
> fix: Support non-DFG circuits

- tket2/src/passes.rs
- tket2/src/passes/tuple_unpack.rs
- tket2/src/rewrite.rs
Adds a pass for removing tuple packs immediately followed by tuple unpacks.
Currently this only removes one-to-one connections.
The code should work for one-to-many, but there's a bug in hugr's `SimpleRewrite` that prevents us from having replacements where multiple outputs are connected to a single input.
See https://github.com/CQCL/hugr/issues/1190.
Closes #380
> feat: tuple unpack rewrite

- tket2-py/src/passes/chunks.rs
- tket2/src/extension.rs
- tket2/src/ops.rs
- tket2/src/passes/commutation.rs
- tket2/src/passes/pytket.rs
- tket2/src/serialize/pytket.rs
- tket2/src/serialize/pytket/decoder.rs
- tket2/src/serialize/pytket/encoder.rs
- tket2/src/serialize/pytket/op.rs
- tket2/src/serialize/pytket/op/native.rs
- tket2/src/serialize/pytket/op/serialised.rs
- tket2/src/serialize/pytket/tests.rs
This is a noisy internal refactor of `::serialize::pytket::op::JsonOp`, extracted from the work towards #379.
`JsonOp` was a temporary structure used during the encoding/decoding of pytket circuits that represented two different kinds of operation:
- pytket operations with a direct tket2 counterpart
- other operations that have to be encoded as OpaqueOps
This mixed up the two definitions, and made applying custom logic to one of the variants more annoying.
(E.g. the special handling of bit input/outputs for tket2 ops needed for #379).
This PR splits the structs into a `Native` and an `Opaque` variant, so we can keep the implementation clean. The code is functionally the same.
> refactor: Cleanup tket1 serialized op structures

- DEVELOPMENT.md
- README.md
- tket2-py/README.md
- tket2/README.md
Updates the python README before release, and brings some updates to DEVELOPMENT.md from hugr.
Let's mark the first release version for `release-please` here:
Release-As: 0.1.0a1
> docs: Update tket2-py readme

- tket2/src/portmatching/pattern.rs
If the pattern had empty wires, `try_from_circuit` failed with a `NotConnected` error. This adds an `EmptyWire` variant instead.
> docs: Better error reporting in portmatching

- Cargo.lock
- tket2-py/Cargo.toml
- tket2-py/src/circuit.rs
- tket2-py/src/circuit/convert.rs
- tket2-py/src/circuit/tk2circuit.rs
- tket2-py/src/optimiser.rs
- tket2-py/src/passes.rs
- tket2-py/src/passes/chunks.rs
- tket2-py/src/pattern/portmatching.rs
- tket2-py/src/utils.rs
Avoids unwrapping the hugr inside `Tk2Circuit`.
This caused problems with circuits with non-root parents. Circuits defined in guppy ended up pointing to the root module instead of the chosen function definition.
Adds the first rust-side test for `tket2-py`.
I'm pretty sure I'll have to install the python interpreter in the CI rust test job, but let's see the error first.
> fix(tket2-py): Replace `with_hugr` helpers with `with_circ`, keeping the circuit parent.

- tket2-py/src/passes.rs
- tket2-py/tket2/_tket2/passes.pyi
- tket2-py/tket2/passes.py
This is used to normalise guppy functions into flat pytket-like circuits.
This is useful for using as pattern match rules.
We may remove the method from `tket2.passes` later, but it's useful to have as an internal binding in `tket2._tket2.passes`.
> feat(tket2-py): Bind the `lower_to_pytket` pass in python

- tket2/src/portmatching.rs
- tket2/src/portmatching/pattern.rs
Patterns with constant value definitions failed at construction time, because the code only read the wire types from the dataflow signature (which does not include const wires).
> fix: Portmatching not matching const edges

- tket2/src/portmatching/matcher.rs
Ignores the `description` field (and the derived `signature`) when comparing custom ops in the pattern matching.
> fix: Pattern matcher discriminating on opaqueOp description

- tket2/src/circuit.rs
- tket2/src/circuit/extract_dfg.rs
- tket2/src/passes/pytket.rs
When replacing a CFG's output with the correct DFG output operation, we inserted the new node at the end of the container's children, instead of just after the input.
Includes a new unit test which simulates a circuit definition from guppy, where we can run the `lower_to_pytket` pass.
> fix: `extract_dfg` inserting the output node with an invalid child order

- tket2-py/src/pattern.rs
- tket2-py/tket2/_tket2/pattern.pyi
Just a couple of helper methods I found useful for debugging.
> feat: Add `lhs` and `rhs` bindings to `Rule`

- Cargo.lock
- Cargo.toml
- tket2/src/circuit.rs
- tket2/src/circuit/command.rs
- tket2/src/circuit/extract_dfg.rs
- tket2/src/passes/chunks.rs
- tket2/src/passes/pytket.rs
- tket2/src/serialize/pytket/decoder.rs
- tket2/src/utils.rs
> chore: Update to hugr 0.6.0, fix breaking changes

- tket2-py/examples/1-Getting-Started.ipynb
No need to rebuild the same guppy function
> docs: simplify the getting started notebook

- tket2/src/passes/tuple_unpack.rs
This was already implemented, but blocked by a bug in hugr (https://github.com/CQCL/hugr/pull/1191).
drive-by: Added a test case for #416, the last missing case for tuple unpacking
> feat: Support tuple unpacking with multiple unpacks

- tket2-hseries/src/extension.rs
- tket2-hseries/src/extension/quantum_lazy.rs
- tket2-hseries/src/extension/result.rs
> feat: add results extensions

- tket2/src/passes/tuple_unpack.rs
Closes #416.
Requires ~https://github.com/CQCL/hugr/issues/1295~ https://github.com/CQCL/hugr/pull/1324 to be released.
> feat: Partial tuple unpack

- tket2/src/optimiser/badger.rs
Coverage checks for #495 showed a hole in coverage for the Badger optimiser, when using multi-threading with circuit splitting. This PR fixes this.
> test: Add coverage for Badger split circuit multi-threading

- badger-optimiser/src/main.rs
- tket2-py/src/optimiser.rs
- tket2-py/src/passes.rs
- tket2-py/tket2/_tket2/passes.pyi
- tket2-py/tket2/passes.py
- tket2/src/optimiser/badger.rs
#496 introduced a new timeout criterion for Badger based on the number of circuits seen during optimisation. This was not consistently exposed to the Python API.
Fly-by: The `progress_timeout` timeout criterion that was added in #259 was also not exposed properly. This PR also fixes this.
The timeout option `max_circuit_cnt` is now called `max_circuit_count`.
> feat: Expose advanced Badger timeout options to tket2-py

- Cargo.toml
- tket2/build.rs
Rust 1.80 [just dropped](https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html), adding a lint option that allows us to avoid the `build.rs` definition added in https://github.com/CQCL/tket2/pull/386.
(The nightly lint got updated before hitting beta, so there shouldn't be compatibility problems there).
> chore: Replace build.rs with lint config in Cargo.toml

- DEVELOPMENT.md
Updates the instructions to use release-plz locally. This is easier and less error prone, since it can reuse the configuration used for normal releases.
This change was copied from https://github.com/CQCL/hugr/pull/1368.
> docs: Update instructions for doing patch releases

- release-please-config.json
Small change so that `release-please`'s PR include a `(py)` tag in their title.
I also enabled separated PRs for the packages, since we don't want to release `tket2-eccs` unless needed.
> ci: Separate release-please PRs, and set a better title

- .github/workflows/python-pure-wheels.yml
- .github/workflows/python-wheels.yml
- Stops the wheel building jobs from running on releases of other packages.
Adding a release for `tket2-eccs` caused `tket2` wheels to be built. Since that's an expensive workflow, this filters it out.
We continue to build for all platforms on each commit to `main`. We may want to skip some platforms in the future.
- Splits the pypi token used for publishing `tket2-py` and `tket2-eccs`.
Scoped tokens only give permissions to a single project. Splitting the tokens here will let us replace the currently unrestricted token.
> ci: Avoid building wheels on unrelated releases, split pypi tokens

- release-plz.toml
Stops releases from being created by new packages pushed to `main`.
https://release-plz.ieni.dev/docs/config#the-release_always-field
This saves us from having to temporarily configure `git_tag_enable` and `git_release_enable` for each crate. https://github.com/CQCL/tket2/pull/519/commits/73d6e651c7cebc6758ac7957a6ff9c7aee1f9419
> chore: Only `release-plz` after release PRs

- tket2/src/circuit.rs
Updates a test that was waiting for a new hugr release
> chore: Remove TODO in test

- poetry.lock
- pyproject.toml
- release-please-config.json
Update to the latest hugr-py version.
I added `pyproject.toml` to the release-please files, so hopefully it should catch it and make a release PR for tket2-py.
BREAKING CHANGE: Breaking dependency update to `hugr 0.7.0`
> chore!: Update hugr-py to `0.7.0`

- .github/workflows/release-plz.yml
This should solve the issue where CI checks wouldn't run in release PRs unless a human triggered an update.
See https://github.com/MarcoIeni/release-plz/blob/main/website/docs/github/token.md#use-a-personal-access-token
> ci: Ensure release-plz always pushes as @hugbot

- .github/workflows/ci.yml
Copies the idea from `hugr`. 
For the rust checks, the CI ran nightly tests followed by the same tests with coverage instrumentation. This added unnecessary delay to the coverage report.
This PR merges the two steps, so the rust codecov analysis should appear ~2:30 minutes faster.
For python, running with and without coverage takes almost the same time. The PR merges the test runs, but still leaves the codecov upload in a separate job (outside the critical path of the required checks). This saves ~1:30.
Before (Coverage delay ~5mins):
After (Coverage delay ~2mins):
> ci: Faster coverage tests

- .pre-commit-config.yaml
Ensures that the checks run by pre-commit are the same as the ones run in CI, and the `ruff` and `mypy` versions are always controlled by `pyproject.toml`.
Before, we used pre-commit actions with their own versions that needed to be updated separately and tended to get out of date.
> chore: Use local ruff and mypy for pre-commit checks

- tket2/src/extension.rs
- tket2/src/extension/angle.rs
Closes #576
BREAKING CHANGE: Angle type not parametric on log denominator. Aconvert op removed, along with type paramateric helper functions
> feat!: angle type no longer parametric.

- .github/workflows/python-wheels.yml
- justfile
Fixes #586, which was broken when we moved `pyproject.toml` in #546.
Running `maturin build` from the root dir tries to build the workspace project, creating an invalid wheel name. This PR updates the ci job and the `just build` command to run maturin from inside `/hugr-py/`.
Maturin is still configured as a build tool in the workspace so that `maturin develop` works everywhere. In that case we don't care about the project name.
> ci: Fix incorrect wheels name on publish

- .github/workflows/python-wheels.yml
Fixes the fix from #587.
I edited the workflow to run in the PR, so we can test it works (without an api key) 
Closes #586
> ci: Fix wheels upload on different dir

- tket2-hseries/src/extension/futures.rs
- tket2-hseries/src/extension/hseries.rs
- tket2-hseries/src/extension/result.rs
- tket2-hseries/src/lazify_measure.rs
- tket2-hseries/src/lib.rs
- tket2-py/src/circuit/tk2circuit.rs
- tket2/src/circuit/cost.rs
- tket2/src/ops.rs
- tket2/src/passes/commutation.rs
- tket2/src/serialize/pytket/op.rs
BREAKING CHANGE: TryFrom implementations for extension op structs removed, use `cast`
> fix!: remove TryFrom for extension ops use `cast`

- tket2-hseries/src/extension/futures.rs
- tket2-hseries/src/extension/hseries.rs
- tket2-hseries/src/extension/result.rs
- tket2/src/extension/angle.rs
- tket2/src/ops.rs
> fix: extension ops checking against incorrect name

- Cargo.lock
- Cargo.toml
- tket2-hseries/Cargo.toml
- tket2-hseries/src/extension/hseries.rs
- tket2-hseries/src/extension/hseries/lower.rs
- tket2-hseries/src/lib.rs
- tket2/src/passes.rs
Closes #490 
Using definitions in hqslib1 https://github.com/CQCL/pytket-quantinuum/blob/main/pytket/extensions/quantinuum/backends/hqslib1.inc
> feat: lowering tk2ops -> hseriesops

- tket2/src/extension/angle.rs
> fix: angle type docstring to say 2pi

- .pre-commit-config.yaml
- justfile
- tket2/src/extension.rs
- tket2/src/extension/sympy.rs
- tket2/src/ops.rs
- uv.lock
Replaces the ad-hoc definition of sympy operations with an opdef / concrete op pair that can be `cast`ed to.
We need this for the _tket2->pytket_ encoder.
Added temporary re-exports to keep this change non-breaking.
Includes #615
> feat: Add an explicit struct for the tket2 sympy op

- tket2-py/tket2/extensions/_json_defs/tket2/rotation.json
- tket2/src/extension/rotation.rs
- tket2/src/serialize/pytket.rs
- tket2/src/serialize/pytket/encoder.rs
- tket2/src/serialize/pytket/op.rs
- tket2/src/serialize/pytket/tests.rs
So we can encode circuits that either encode sympy expressions, or use the float extension to manipulate the rotations.
Note that this does not yet support `RotationOps::from_halfturns`, since that returns an `Option<Rotation>` since unwrapping that requires control flow operations, so the parameter encoder would need to do constant propagation with parameters across control flow...
drive-by: Mention that `RotationOps::from_halfturns` is fallible in its description. This required a non-breaking update to the extension's `json` definition.
> feat: Support encoding float and sympy ops

- tket2-py/tket2/extensions/_json_defs/tket2/rotation.json
- tket2/src/extension/rotation.rs
- tket2/src/serialize/pytket/encoder.rs
- tket2/src/serialize/pytket/tests.rs
This is an operation that we are able to process while encoding pytket circuits.
We expect guppy to emit this instead of adding explicit panics to unwrap the fallible result.
The pytket encoder should now support float wires.
Closes #630
I'll open a followup issue on guppy
> feat: Add `tket2.rotation.from_halfturns_unchecked` op

- Cargo.lock
- Cargo.toml
- tket2/Cargo.toml
- tket2/src/circuit.rs
- tket2/src/ops.rs
- tket2/src/serialize/pytket.rs
- tket2/src/serialize/pytket/decoder.rs
- tket2/src/serialize/pytket/encoder.rs
- tket2/src/serialize/pytket/op/native.rs
- tket2/src/serialize/pytket/param.rs
- tket2/src/serialize/pytket/param/decode.rs
- tket2/src/serialize/pytket/param/encode.rs
- tket2/src/serialize/pytket/param/param.pest
- tket2/src/serialize/pytket/tests.rs
- tket2/tests/badger_termination.rs
This is an alternative to #635, using pure-rust instead of calling to python so we can keep the pytket decoder on the `tket2` crate.
Improves parsing of pytket operation parameters by defining a grammar and parser for sympy expressions using `pest` (based on the [calculator example](https://pest.rs/book/examples/calculator.html) for infix operation precedence).
- Unrecognized operations are still put inside an opaque `SympyOp`, but that should be easy to change in the future.
- I tested multiple sympy expressions to ensure we are able to parse them, but unrecognized ones will also fallback to `SympyOp`.
This is still missing routing parameters to hugr inputs (#628), as it is blocked by https://github.com/CQCL/hugr/issues/1562.
drive-by: Move the pytket parameter encoding/decoding routines …
> feat: Decode pytket op parameters

- .github/workflows/ci.yml
- .github/workflows/python-pure-wheels.yml
- tket2-eccs/pyproject.toml
- tket2-py/pyproject.toml
- uv.lock
This reverts commit d8b5150d816fa5a543aa8244104c44870f1c2da5.
`tket2` depends on `pytket`, which does not currently publish wheels for `python 3.13`.
We'll have to wait for them to update this package.
> revert: "Support python 3.13 (#653)"

- tket2/src/extension.rs
- tket2/src/ops.rs
- tket2/src/optimiser/badger.rs
- tket2/src/passes/commutation.rs
- tket2/src/rewrite/strategy.rs
- tket2/src/rewrite/trace.rs
Drops some deprecated exports.
drive-by: Remove a couple TODOs about impl iterators.
BREAKING CHANGE: Renamed `LexicographicCostFunction::default_cx` to `LexicographicCostFunction::default_cx_strategy`. Removed sympy constant re-exports in `sympy::extension`.
> refactor!: Remove deprecated exports

- Cargo.lock
- Cargo.toml
- tket2-py/Cargo.toml
- tket2-py/src/circuit/tk2circuit.rs
- tket2/Cargo.toml
- tket2/src/circuit/extract_dfg.rs
- tket2/src/serialize/guppy.rs
We can now drop the dependency on `hugr-cli` for `tket2{,-py}`.
Hugr roots now have (disconnected) ports, so I had to fix the low-level `rewrite_dfg` to ensure we keep the root valid.
> chore: Update to `hugr 0.13.2`, fix deprecation warnings

- .github/workflows/ci.yml
We'll try to use the current lock file, instead of failing if the uv.lock get's update (by e.g. a minor dependency bump)
> ci: Use `uv --frozen` instead of `--locked`

- .github/workflows/ci.yml
- .github/workflows/python-pure-wheels.yml
- tket2-eccs/pyproject.toml
- tket2-py/pyproject.toml
- uv.lock
Let's try #653 again.
The [latest `pytket`](https://github.com/CQCL/tket/releases/tag/1.34.0) supports python `3.13`, so we can update here.
We now follow the [general](https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special) [recommendation](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#python-requires) against setting a hard python version bound in the `pyproject.toml`'s `requires-python` field.
> chore(py): Support python 3.13

- .github/workflows/python-pure-wheels.yml
- tket2-exts/README.md
contains a trivial readme change so I can test publishing a patch update to tket2-exts
https://docs.pypi.org/trusted-publishers/using-a-publisher/
https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment
> refactor: setup pypi trusted publishing

- .github/workflows/python-pure-wheels.yml
Fixes the error seen in
https://github.com/CQCL/tket2/actions/runs/11687531591/job/32546324705#step:6:19
This is the way to skip the rest of the job, at least until https://github.com/orgs/community/discussions/82744 gets implemented.
> ci: Fix ci error on pure-wheels run for unchanged packages

- .github/workflows/ci.yml
- codecov.yml
At some point it seems the python coverage step started failing ~~due to some invalid auto-discovered coverage files (I think `download-artifact` creates a directory with the file's name, and we ended up with a `IsADirectoryError`)~~.
https://github.com/CQCL/tket2/actions/runs/11706568650/job/32604131200?pr=680#step:4:57
This change tries to fix that by disabling the automatic discovery, and makes the step fail if the upload fails in the future.
drive-by: Copy `codecov.yml` config from hugr
> ci: Fix py coverage not getting uploaded

- .github/workflows/ci.yml
- .github/workflows/semver-checks.yml
Fixes the errors we've seen with dependabot PRs (and fork PRs) failing the checks.
See https://github.com/CQCL/hugrverse-actions/issues/20
drive-by: Trigger the normal CI checks on any pull request, not only the ones targeting `main`
> ci: run semver-checks on a `pull_request_target` trigger

- Cargo.lock
- Cargo.toml
- tket2-hseries/src/extension/futures.rs
- tket2-hseries/src/extension/hseries.rs
- tket2-hseries/src/extension/hseries/lower.rs
- tket2-hseries/src/extension/result.rs
- tket2/src/circuit.rs
- tket2/src/extension.rs
- tket2/src/extension/rotation.rs
- tket2/src/extension/sympy.rs
- tket2/src/ops.rs
- tket2/src/portmatching/pattern.rs
- tket2/src/serialize.rs
Awaiting release
BREAKING CHANGE: Extension definitions and registries use `Arc` for sharing
> refactor!: update to hugr 0.14

- tket2-exts/src/tket2_exts/data/tket2/hseries.json
- tket2-exts/src/tket2_exts/data/tket2/quantum.json
- tket2-hseries/src/extension/hseries.rs
- tket2-hseries/src/extension/hseries/lower.rs
- tket2-hseries/src/lib.rs
- tket2-py/tket2/ops.py
- tket2/src/extension.rs
- tket2/src/ops.rs
- tket2/src/serialize/pytket/op/native.rs
- uv.lock
Closes #691 Closes #692 Closes #693
- Add TryQAlloc and MeasureFree to "tket2.quantum"
- Lower new ops to "tket2.hseries"
- Add MeasureReset to "tket2.hseries"
BREAKING CHANGE: hseries qalloc op replaced with fallible TryQalloc
> feat!: update measurement and alloc operations

- .github/workflows/python-wheels.yml
- tket2-py/Cargo.toml
test wheels building run:
https://github.com/CQCL/tket2/actions/runs/12357204894
Closes #724 
drive-by: Update `macos` runner for the mac x86 wheels build job to `macos-13`, as `-12` has been deprecated.
> ci: Build wheels using the python's stable ABI

- Cargo.lock
- Cargo.toml
- tket2-hseries/src/lib.rs
Currently waiting for the package releases.
Requires the fix in https://github.com/CQCL/portgraph/pull/178.
BREAKING CHANGE: Bumped `hugr` dependency to `0.15`
> chore!: Update `hugr 0.14.3`, `portgraph 0.13.1`, and `petgraph 0.7.1`

- tket2-exts/src/tket2_exts/__init__.py
- tket2-exts/src/tket2_exts/data/tket2/qsystem/random.json
- tket2-hseries/src/bin/tket2-hseries.rs
- tket2-hseries/src/extension.rs
- tket2-hseries/src/extension/random.rs
- tket2-hseries/src/extension/utils.rs
Closes: #748
Apart from the signatures in the reporting issue, I had to include an additional function to discard the linear context.
```rust
/// fn delete_rng_context(RNGContext) -> ()
DeleteContext,
```
Appreciate other ideas to discard the context.
> feat: add "tket2.qsystem.random" extension

- tket2-py/pyproject.toml
- tket2-py/tket2/extensions/__init__.py
I forgot to edit `tket2-py/tket2/extensions/__init__.py` in #779 
Need to bump version constraint for tket2-exts to be able to use it in guppy at https://github.com/CQCL/guppylang/pull/806
> fix: include RNG extension in tket2-py, bump tket2-exts constraint

- tket2-exts/src/tket2_exts/data/tket2/qsystem/random.json
- tket2-hseries/src/extension/random.rs
See https://github.com/CQCL/guppylang/pull/822
BREAKING CHANGE: To be compatible with Guppy's convention of implicitly returning `self` as the second value of the tuple, the following signatures are updated:
```diff
-    /// `fn random_int(RNGContext) -> (RNGContext, u32)`
+   /// `fn random_int(RNGContext) -> (u32, RNGContext)`
-   /// `fn random_float(RNGContext) -> (RNGContext, f32)`
+   /// `fn random_float(RNGContext) -> (f32, RNGContext)`
-   /// `fn random_int_bounded(RNGContext, bound: u32) -> (RNGContext, u32)`
+   /// `fn random_int_bounded(RNGContext, bound: u32) -> (u32, RNGContext)`
```
> fix!: remove type argument from `RNGContext` type, swap returns

- tket2-exts/src/tket2_exts/data/tket2/qsystem/utils.json
- tket2-hseries/src/extension/utils.rs
- tket2-py/src/circuit/tk2circuit.rs
Revert #792 
BREAKING CHANGE: Make `UtilsOp` enum `non_exhaustive` so that future additions are not considered API-breaking.
> fix(tket2-hseries)!: rm unneeded ext, make `UtilsOp` enum `non_exhaustive`

- Cargo.lock
- Cargo.toml
- tket2-exts/pyproject.toml
- tket2-hseries/src/extension/qsystem/lower.rs
- tket2-hseries/src/lazify_measure.rs
- tket2-hseries/src/lib.rs
- tket2-py/examples/utils/__init__.py
- tket2-py/pyproject.toml
- tket2-py/src/pattern.rs
- tket2-py/tket2/circuit/build.py
- tket2/src/circuit.rs
- tket2/src/circuit/command.rs
- tket2/src/circuit/hash.rs
- tket2/src/circuit/units.rs
- tket2/src/circuit/units/filter.rs
- tket2/src/optimiser/badger.rs
- tket2/src/passes/commutation.rs
- tket2/src/passes/pytket.rs
- tket2/src/passes/tuple_unpack.rs
- tket2/src/portmatching/matcher.rs
- tket2/src/portmatching/pattern.rs
- tket2/src/rewrite.rs
- tket2/src/rewrite/ecc_rewriter.rs
- tket2/src/rewrite/strategy.rs
- tket2/src/serialize.rs
- tket2/src/serialize/pytket/encoder.rs
- uv.lock
wait for release
mainly cherry pick from 6f171b772bdefe7cb9f13e027bd950b19b40e93a
BREAKING CHANGE: `Node` is now an associated type of `HugrView`
BREAKING CHANGE: `Circuit::load_function_reader` takes a `BufRead` rather than `Read`
> chore!: bump to hugr-rs 0.15 and hugr-py 0.11

- devenv.lock
- devenv.nix
- devenv.yaml
I started getting link errors on uv sync with mismatched symbols
this repo no longer requires the llvm package, removing it fixed my problems
> chore: devenv cleanups

- .github/workflows/unsoundness.yml
- justfile
Copied straight from CQCL/hugr
- Runs the miri test weekly instead of on each push to main
- Open an issue on the repo when the test fails
- Adds a `just miri` recipe to check unsoundness locally
We should wait until #818 gets merged before adding this.
> ci: Update miri tests workflow, add justfile recipe

- Cargo.lock
- Cargo.toml
- tket2-hseries/src/extension/qsystem.rs
- tket2/src/extension/bool.rs
Wait to merge for hugr 0.15.3 release including https://github.com/CQCL/hugr/pull/2032
> refactor: Better error message on allocation failure.

- tket2/src/circuit.rs
- tket2/src/circuit/command.rs
- tket2/src/circuit/units.rs
- tket2/src/rewrite.rs
- tket2/src/serialize.rs
The update to `hugr 0.15` added a `Node` associated type to `HugrView`.
Over here, that got implemented as a new type parameter in `Circuit`,
```rust
struct Circuit<T = Hugr, N = Node>
```
All `impl` blocks however restrain it to the specific hugr support,
```rust
impl<T: HugrView> Circuit<T, T::Node> { ... }
```
Given how both types are connected, we should be using `T::Node` directly since an unrelated node type is not usable here.
This PR changes the definition to
```rust
pub struct Circuit<T: HugrView = Hugr>
```
As this is a breaking change, it can wait until the next breaking release.
BREAKING CHANGE: Removed node type parameter from `Circuit`
> refactor!: Remove node parameter from Circuit

- tket2-exts/src/tket2_exts/data/tket2/qsystem.json
- tket2-hseries/src/extension/qsystem.rs
Closes #850
BREAKING CHANGE: ZZMax removed from Qsystem extension. Use ZZPhase(pi/2).
> feat(hseries)!: remove ZZMax operation from Qsystem extension

- .github/workflows/release-checks.yml
Checks that the tests run correctly against the latets published `tket2-exts` and `tket2-eccs`.
If this fails, we may need to publish a new version of those first.
Passing check: https://github.com/CQCL/tket2/actions/runs/15108368429/job/42461967318
> ci: Test `tket2-py` release PRs using released `-exts` and `-eccs`

- Cargo.lock
- tket2-hseries/Cargo.toml
- tket2-hseries/src/extension/qsystem/barrier/barrier_ops.rs
- tket2-hseries/src/extension/qsystem/lower.rs
Replaces HashMap with BTreeMap and IndexMap (`OpHashWrapper` is not `Ord` so can't use `BTreeMap`) as appropriate.
> fix(tket2-hseries): ensure deterministic lowering using maps

- tket2-hseries/src/extension/qsystem.rs
> refactor(tket2-hseries): use smaller angle decompositions for CZ and CCX

- .github/workflows/ci.yml
This should match tags like `tket2-v0.12.1` or `tket2-exts-v0.9.1`.
Looks like I accidentally added some extra characters.
> ci: Fix typo in tag match expression

- Cargo.lock
- Cargo.toml
- tket2-hseries/src/extension/wasm.rs
This replaces `TypeArg::Tuple` with `TypeArg::List` in the construction of a function type. It also changes the `Cargo.toml` to use the main branch of `hugr` so that https://github.com/CQCL/hugr/pull/2378 is integrated, fixing more test failures.
There's now one remaining test failure, related to https://github.com/CQCL/hugr/issues/2387. It's unclear to me whether that is to be fixed in `tket2` or in `hugr`.
> fix: Use `TypeArg::List` instead of `TypeArg::Tuple`

- .github/workflows/release-plz.yml
Includes the changes from https://github.com/CQCL/hugr/pull/2472 to avoid release-plz closing release PRs due to dataraces.
> ci: Setup trusted Crates.io publishing

- Cargo.lock
- Cargo.toml
- tket-qsystem/src/lib.rs
- tket-qsystem/src/lower_drops.rs
Add LowerDropsPass, use in QSystemPass.
hugr 0.22.0 -> 0.22.1 gets the "copy_discard_array" being in the default ReplaceTypes
> feat: Lower "Drop" op in guppy extension, update hugr minor version

- .github/workflows/python-wheels.yml
See: https://www.maturin.rs/distribution.html#using-pypis-trusted-publishing
> ci: switch to trusted publishing for tket pypi

- .github/workflows/release-checks.yml
Brings in fixes from https://github.com/CQCL/guppylang/pull/1150
We were filtering the _target_ branch instead of the source, so this never ran.
> ci: Fix release-checks trigger filter

- .github/workflows/release-checks.yml
The `release-checks` workflow is not actually trigger on release PRs.
We already fixed this when implementing the workflow in guppy, I'm backporting the changes here.
> ci: Fix release-checks trigger

- tket-exts/src/tket_exts/data/tket/wasm.json
- tket-qsystem/src/extension/wasm.rs
Upstream changes to the WASM extension from the `gpu` branch. Namely,
* Add a new type `Result`, which can be lazily read to get the operation result and return the context
* The `call` operation returns a `Result` instead of a context + future
* Functions can now be looked up either by name or by id in the wasm module
* `ConstWasmModule` no longer contains a `hash` field (that we weren't using) and its other field has been renamed
BREAKING CHANGE: This is a breaking change to the WASM extension and its serialised representation
> feat!: Update WASM extension

- tket-py/src/ops.rs
- tket-qsystem/src/pytket/qsystem.rs
- tket-qsystem/src/pytket/tests.rs
- tket/src/serialize/pytket/decoder.rs
- tket/src/serialize/pytket/decoder/param.rs
- tket/src/serialize/pytket/decoder/param/parser.rs
- tket/src/serialize/pytket/decoder/wires.rs
- tket/src/serialize/pytket/encoder.rs
- tket/src/serialize/pytket/extension.rs
- tket/src/serialize/pytket/extension/bool.rs
- tket/src/serialize/pytket/extension/float.rs
- tket/src/serialize/pytket/extension/prelude.rs
- tket/src/serialize/pytket/extension/rotation.rs
- tket/src/serialize/pytket/extension/tk1.rs
- tket/src/serialize/pytket/extension/tket.rs
- tket/src/serialize/pytket/tests.rs
- uv.lock
Fixes inconsistent encoding/decoding parameters. Now we keep them in _half-turns_ most of the time, unless an specific operation requires them to be in radians.
- The `ParameterType` used while decoding now has variants `Rotation | FloatHalfTurns | FloatRadians`.
Operation decoders must now specify which one they expect for their inputs.
- Decoding a pytket parameter emits float operations over `FloatHalfTurns`, to avoid unnecessary conversions from/to radians.
- The encoder always stores parameters expressions in half-turns, `qsystem` ops must then add a `/ pi` before emitting their command.
BREAKING CHANGE: (pytket decoder) Renamed `LoadedParameterType` to `ParameterType` and changed its variants.
BREAKING CHANGE: (pytket decoder) Made `LoadedParameter` attributes private, and modified …
> fix!: Fix rotation -> float param type conversion

- tket/src/extension.rs
- tket/src/serialize/pytket.rs
- tket/src/serialize/pytket/decoder.rs
- tket/src/serialize/pytket/decoder/wires.rs
- tket/src/serialize/pytket/encoder.rs
- tket/src/serialize/pytket/encoder/value_tracker.rs
- tket/src/serialize/pytket/tests.rs
Now the permutation gets reflected in the wire structure.
A `(circ := Circuit(2).SWAP(0,1)).replace_SWAPs()` now gets encoded directly as
```mermaid
graph LR
subgraph 0 ["(0) Module"]
direction LR
subgraph 1 ["(1) [**FuncDefn: #quot;#quot;**]"]
direction LR
style 1 stroke:#832561,stroke-width:3px
2["(2) Input"]
3["(3) Output"]
2--"0:1<br>qubit"-->3
2--"1:0<br>qubit"-->3
end
end
```
Before we only stored the permutation in the circuit's metadata
> feat: Capture pytket's output permutation explicitly in the hugr connectivity

- tket-qsystem/src/pytket/qsystem.rs
- tket/src/serialize/pytket/config/decoder_config.rs
- tket/src/serialize/pytket/decoder.rs
- tket/src/serialize/pytket/decoder/wires.rs
- tket/src/serialize/pytket/extension.rs
- tket/src/serialize/pytket/extension/bool.rs
- tket/src/serialize/pytket/extension/prelude.rs
- tket/src/serialize/pytket/extension/tk1.rs
- tket/src/serialize/pytket/extension/tket.rs
`LoadedParameter` is `Copy`, so wrapping them in an Arc in unnecessary bookeeping/indirection.
BREAKING CHANGE: Removed Arc from `PytketDecoder::op_to_hugr` parameters
> feat!: Remove unnecessary Arc from PytketDecoder method

- tket/src/serialize/pytket/encoder.rs
When encoding ops into pytket circuits we were comparing ids against the circuit's I/O nodes.
This ended up producing unsupported ops in the encoding of nested regions (when emitting CircBoxes).
No test here yet, they'll be added with the implementation of #44.
> fix(pytket-encoder): Correctly encode I/O nodes in nested containers

- tket-qsystem/tests/guppy_opt.rs
Add test pass runs over the circuits from #904.
Some notable issues:
- The constant folding pass (and DCE) fails on some cases, leaving unconnected qubit ports.
https://github.com/CQCL/hugr/issues/2557
Should be fixed on https://github.com/CQCL/hugr/pull/2560
- (Requires Hugr `0.22.4` / `0.23` release)
- The basic-block merge rewrite should define a composable pass.
https://github.com/CQCL/hugr/issues/2556
- We are missing a simple `InlineCFG` pass to unwrap simple linear CFGs. (Either single blocks, or it can be conbined with `merge_bbs`).
https://github.com/CQCL/hugr/issues/945
If we fix those, we should be able to `assert!` that some of the examples here optimize to the identity.
We'll need to call pytket optimisations for the rest.
- ~Requires a `hugr 0.22.3` release with this fix: …
> test: Optimize and validate guppy hugr examples

- Cargo.lock
- Cargo.toml
- tket/src/serialize/pytket.rs
- tket/src/serialize/pytket/decoder.rs
- tket/src/serialize/pytket/decoder/param.rs
- tket/src/serialize/pytket/decoder/wires.rs
- tket/src/serialize/pytket/options.rs
- tket/src/serialize/pytket/tests.rs
Followup from #1120. Adds the option to decode a pytket circuit into a DFG in the Hugr, rather than a standalone function.
> feat: Decode pytket circs into DFGs

- tket-qsystem/src/pytket/qsystem.rs
- tket/src/serialize/pytket/decoder.rs
- tket/src/serialize/pytket/encoder.rs
- tket/src/serialize/pytket/error.rs
- tket/src/serialize/pytket/extension/bool.rs
- tket/src/serialize/pytket/extension/core.rs
- tket/src/serialize/pytket/extension/prelude.rs
- tket/src/serialize/pytket/extension/tk1.rs
- tket/src/serialize/pytket/extension/tket.rs
Expands support for defining which qubit and bit ids get used for the outputs when encoding and decoding pytket operations.
On the decoder side, splits the `qubits: &[TrackedQubit]` and `bits: &[TrackedBit]`  parameters of the wiring-up operation into `input_` and `output_` lists, so both can be set explicitly.
On the encoder site, since the behaviour is a bit more complex (the input ids are not immediately known without some extra computation) we add a `EmitCommandOptions` struct with functions that mark which ids to reuse, and methods to easily set commonly used options.
Blocked by
- #1120
- #1121 
- (Requires Hugr `0.22.4` / `0.23` release)
- #1123
- #1122
Closes #1124 
BREAKING CHANGE: `PytketEncoderContext::emit_node` and `PytketDecoderContext::add_node_with_wires` now explicitly …
> feat(pytket-decoder)!: Allow specifying qubit/bit reuse

- release-please-config.json
The `__init__.py` is not in a default location, so we must add it explicitly here for `release-please` to detect the `x-release-please-version` annotation and update the package's `__version__` constant
> chore: Ensure release-please updates qis-compiler's __version__
